name: remote-wallet

services:
  nostr-relay:
    image: scsibug/nostr-rs-relay:0.9.0
    ports:
      - "8080:8080"
  solana-test-validator:
    image: beeman/solana-test-validator:4.0.0
    ports:
      - "8899:8899"
      - "8900:8900"
    security_opt:
      - seccomp=unconfined
    stdin_open: true
    tty: true
